### ISSUE TITLE
Doesn't work in redmine 1.4.2

### ISSUE THREAD

**Issue by ilya-il** [masamitsu-murase/redmine_add_subversion_links#5]
Hi! Add subversion links 0.0.4  doesn't work with redmine 1.4.2. The error is:

```
Processing RepositoriesController#show (for 10.0.10.232 at 2012-05-22 17:06:47) [GET]
  Parameters: {"id"=>"ifs", "action"=>"show", "controller"=>"repositories"}
Rendering template within layouts/base
Rendering repositories/show

ActionView::TemplateError (undefined method `repository' for #<ActiveRecord::Associations::HasOneAssociation:0x7fa5315997b8>) on line #34 of app/views/repositories/_dir_list_content.html.erb:
31: <td class="size"><%= (entry.size ? number_to_human_size(entry.size) : "?") unless entry.is_dir? %></td>
32: <% changeset = @repository.find_changeset_by_name(entry.lastrev.identifier) if entry.lastrev && entry.lastrev.identifier %>
33: <% if @repository.report_last_commit %>
34: <td class="revision"><%= link_to_revision(changeset, @repository) if changeset %></td>
35: <td class="age"><%= distance_of_time_in_words(entry.lastrev.time, Time.now) if entry.lastrev && entry.lastrev.time %></td>
36: <td class="author"><%= changeset.nil? ? h(Redmine::CodesetUtil.replace_invalid_utf8(entry.lastrev.author.to_s.split('<').first)) : h(changeset.author) if entry.lastrev %></td>
37: <td class="comments"><%=h truncate(changeset.comments, :length => 50) unless changeset.nil? %></td>

    app/views/repositories/_dir_list_content.html.erb:34
    app/views/repositories/_dir_list_content.html.erb:1:in `each'
    app/views/repositories/_dir_list_content.html.erb:1
    app/views/repositories/_dir_list.html.erb:16
    app/views/repositories/show.html.erb:11
    app/controllers/repositories_controller.rb:102:in `show'
    config/initializers/mongrel_cluster_with_rails_211_fix.rb:62:in `dispatch_cgi'

Rendering /opt/redmine/apps/redmine/public/500.html (500 Internal Server Error)
```

Redmine 1.4.2.stable (Bitnami stack)
MySQL 5.5.21
Ruby 1.8.7
Rails 2.3.14
SVN version 1.7.4

I've submitted bug here - http://www.redmine.org/issues/10993
